### ISSUE TITLE
Add validation rule to disallow icon URL using GitHub raw links

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-community-validation#28]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

It would be good to add rules for `iconUrl` validation. These should include a rule that github raw is not allowed to be used, and a rule that rawgit is not allowed as it has shut down. 

### Describe The Solution. Why is it needed?

Lots of packages get pushed to CCR with github raw and with rawgit links. 

### Related Issues

- Issue https://github.com/chocolatey/home/issues/16

**Comment by AdmiringWorm** [comment]
Seeing as this is a new extension, and it runs on the client side. This should probably be implemented as a requirement in this case.
