### ISSUE TITLE
CPMR0001 implementation more strict than package validator.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey-community/chocolatey-community-validation#31]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

When trying to pack a package with an empty checksum element, the CPMR0001 rule get triggered. This does not happen for packages going through the validator.

### What is Expected?

That packages with an empty checksum element do not fail CPMR0001, to be consistent with the validator behavior. 
https://community.chocolatey.org/packages/libreoffice-fresh

### How Did You Get This To Happen?

1. Get the source `libreoffice-fresh` at https://github.com/chocolatey-community/chocolatey-packages/tree/master/automatic/libreoffice-streams
2. Run `choco pack` in the directory
3. See that pack fails with CPMR0001

### System Details

* Operating System: Windows 10 22H2
* Windows PowerShell version: 5.1
* Chocolatey CLI Version: 2.2.2
* Chocolatey Licensed Extension version: N/A
* Chocolatey License type: Open source
* Terminal/Emulator: PowerShell

### Installed Packages

```bash
Not applicable.
```

### Output Log

```bash
https://gist.github.com/TheCakeIsNaOH/8dda18d47a98ebabeae24058ba1d21b1
```

**Comment by AdmiringWorm** [comment]
It is intentional that the rule is stricter than the implementation in package validator. In this, we are taking what the rule description is specified as, instead of doing a 1-to-1 like of the implementation in package validator. If it had been the other way around, that this extension wouldn't have flagged the empty Copyright element, but the package validator had flagged it, this would have been a bug.
